[loggers]
keys=root,framework,app,uvicorn

[handlers]
keys=psqlHandler

[formatters]
keys=normalFormatter,detailedFormatter


[logger_app]
level=DEBUG
handlers=psqlHandler
qualname=app
propagate=0

[logger_framework]
level=DEBUG
handlers=psqlHandler
qualname=framework
propagate=0

[logger_root]
level=DEBUG
handlers=psqlHandler

[logger_uvicorn]
level=ERROR
handlers=psqlHandler
qualname=uvicorn
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=normalFormatter
args=(sys.stdout,)

[handler_detailedConsoleHandler]
class=StreamHandler
level=DEBUG
formatter=detailedFormatter
args=(sys.stdout,)

[handler_psqlHandler]
class=handlers.psql_handler.PsqlHandler
level=NOTSET
formatter=detailedFormatter
args=()

[formatter_normalFormatter]
format=%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s

[formatter_detailedFormatter]
format=%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s   call_trace=%(pathname)s L%(lineno)-4d
